# GitHub Copilot Configuration
# This file tells GitHub Copilot about coding preferences for this repository

# Indentation: Use 2 spaces, no tabs
indent_style = space
indent_size = 2

# File types
[*.gd]
indent_style = space
indent_size = 2

[*.json]
indent_style = space
indent_size = 2

[*.yml]
[*.yaml]
indent_style = space
indent_size = 2
